server:
  port: 8090

hestia:
  console:
    web:
      nodes:
        - node-id: node-1
          node-name: index-1
          base-url: http://127.0.0.1:9001
          agent-token: ""
      refresh-millis: 2500
